apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-echo-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grpc-echo-service.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8443
    protocol: TCP
  selector:
    {{- include "grpc-echo-service.labels" . | nindent 4 }}